apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: lpmc3sa21-go 
  janus-idp.io/tekton: lpmc3sa21-go
  backstage.io/kubernetes-id: lpmc3sa21-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: lpmc3sa21-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml