apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: lpmc3sa21-go-gitops
  description: This is GitOps manifest for lpmc3sa21-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=lpmc3sa21-go
    backstage.io/kubernetes-id: lpmc3sa21-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: lpmc3sa21-go
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:lpmc3sa21-go
