apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: lpmc3sa21-go
  janus-idp.io/tekton: lpmc3sa21-go
  backstage.io/kubernetes-id: lpmc3sa21-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: lpmc3sa21-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
